### ISSUE TITLE
File / directory filtering

### ISSUE THREAD

**Issue by etiennepellegrini** [ozntel/file-tree-alternative#5]
Some filtering options would be great. For instance:
- filter out based on filename and regex
- filter out directories based on name
- allow user inputted maximum depth when displaying a certain dir and subdirs

The main motivation is that I put attachment in a /resources sub-dir in every one of my vault's directory, but I don't want the images showing up in the file tree

**Comment by ozntel** [comment]
Does it help if I include `Excluded File Extensions` option in the settings?

**Comment by ozntel** [comment]
Just release a version, which includes `Folder` and `File` exclusion feature. Please let me know if you have any trouble.

**Comment by etiennepellegrini** [comment]
This is great thanks!
The extension exclusion works great! 
For the directories, I'd love an option to exclude folders by name, not by full path - since I have a "resources" folder in every "real" directory... I tried `*/resources` but it didn't work! Thanks again!

**Comment by ozntel** [comment]
Maybe you can use a CSS snippet like that:

```css
div.treeview > div[data-path*="resources"], div.treeview > div[data-path*="resources"] + div {
	display: none !important;
}
```
