### ISSUE TITLE
off-center guide line?

### ISSUE THREAD

**Issue by eleanorkonik** [ozntel/file-tree-alternative#69]
Is it possible to turn the lines off or restyle them so they're moved? It feels like it's aligned to the "left" but I'd prefer it to be aligned to the "center" or turned off. 

![image](https://user-images.githubusercontent.com/75856959/158245571-51e39160-7248-40da-905c-9f01a7e96563.png)

**Comment by ozntel** [comment]
I changed a little bit style and added margin to the left to make sure that it looks better in the new version. 
But you can always overwrite the following part:

```css
.oz-folder-contents{
    border-left: 2px solid var(--text-accent);
    margin-left: 5px !important;}
```
